// Tailwind config for the prebuilt stylesheet (public/assets/tailwind.css).
// Mirrors the theme that used to live inline with the cdn.tailwindcss.com
// Play CDN. After changing classes in public/index.html, rebuild with:
//   npm run build:css
import forms from "@tailwindcss/forms";

export default {
  content: ["./public/index.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary": "#003919",
        "on-secondary-fixed-variant": "#004e5a",
        "inverse-on-surface": "#2f3132",
        "surface-container": "#1e2021",
        "primary-fixed": "#61ff97",
        "on-tertiary": "#3a3000",
        "surface-container-highest": "#333536",
        "on-background": "#e2e2e3",
        "on-primary-container": "#007137",
        "inverse-surface": "#e2e2e3",
        "on-tertiary-container": "#736000",
        "inverse-primary": "#006d35",
        "text-dim": "#8A9296",
        "tertiary-container": "#ffdc49",
        "surface-container-low": "#1a1c1d",
        "live-red": "#FF3B3B",
        "surface-container-high": "#282a2b",
        "on-primary-fixed": "#00210c",
        "on-secondary-container": "#005f6d",
        "outline": "#849584",
        "on-tertiary-fixed": "#221b00",
        "error-container": "#93000a",
        "tertiary": "#fffaf5",
        "outline-variant": "#3b4b3d",
        "primary-container": "#00ff85",
        "secondary": "#b9f1ff",
        "surface-container-lowest": "#0c0e0f",
        "tertiary-fixed": "#ffe16d",
        "on-surface-variant": "#b9cbb9",
        "error": "#ffb4ab",
        "surface-glass": "rgba(25, 28, 30, 0.6)",
        "on-primary-fixed-variant": "#005227",
        "surface": "#121415",
        "secondary-fixed": "#a5eeff",
        "primary": "#f0ffee",
        "on-error": "#690005",
        "surface-dim": "#121415",
        "secondary-fixed-dim": "#00daf8",
        "background": "#121415",
        "on-secondary-fixed": "#001f25",
        "border-muted": "#1F2427",
        "surface-bright": "#38393a",
        "tertiary-fixed-dim": "#e9c400",
        "secondary-container": "#00e0ff",
        "primary-fixed-dim": "#00e476",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#544600",
        "surface-tint": "#00e476",
        "on-surface": "#e2e2e3",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "9999px",
      },
      spacing: {
        "stack-sm": "0.5rem",
        "container-max": "1280px",
        "stack-lg": "2rem",
        "stack-md": "1rem",
        "margin-mobile": "1rem",
        "gutter": "1.5rem",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        "display-lg": ["Oswald"],
        "label-caps": ["Inter"],
        "headline-lg": ["Oswald"],
        "body-md": ["Inter"],
        "data-tabular": ["JetBrains Mono"],
      },
      fontSize: {
        "display-lg": ["72px", { lineHeight: "80px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "0.02em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "data-tabular": ["14px", { lineHeight: "20px", fontWeight: "500" }],
      },
    },
  },
  plugins: [forms],
};
