// Tailwind config for the prebuilt stylesheet (public/assets/tailwind.css).
// Mirrors the theme that used to live inline with the cdn.tailwindcss.com
// Play CDN. After changing classes in public/index.html, rebuild with:
//   npm run build:css
import forms from "@tailwindcss/forms";

export default {
  content: ["./public/index.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary": "#04220f",
        "on-secondary-fixed-variant": "#06343d",
        "inverse-on-surface": "#2a2d2e",
        "surface-container": "#191c1e",
        "primary-fixed": "#46e08a",
        "on-tertiary": "#2e2600",
        "surface-container-highest": "#272b2e",
        "on-background": "#e6e8e8",
        "on-primary-container": "#0b8a48",
        "inverse-surface": "#e6e8e8",
        "on-tertiary-container": "#6a5900",
        "inverse-primary": "#0b8a48",
        "text-dim": "#6f7877",
        "tertiary-container": "#f2c94c",
        "surface-container-low": "#141618",
        "live-red": "#ef4444",
        "surface-container-high": "#202426",
        "on-primary-fixed": "#04220f",
        "on-secondary-container": "#06343d",
        "outline": "#46504f",
        "on-tertiary-fixed": "#221b00",
        "error-container": "#7a1a1a",
        "tertiary": "#fdfbf7",
        "outline-variant": "#29302f",
        "primary-container": "#1fd97b",
        "secondary": "#bfefff",
        "surface-container-lowest": "#0a0c0d",
        "tertiary-fixed": "#f4cf5a",
        "on-surface-variant": "#9aa4a2",
        "error": "#ffb4ab",
        "surface-glass": "rgba(20, 23, 25, 0.72)",
        "on-primary-fixed-variant": "#0b8a48",
        "surface": "#0e1011",
        "secondary-fixed": "#a9e9ff",
        "primary": "#eef2ef",
        "on-error": "#690005",
        "surface-dim": "#0e1011",
        "secondary-fixed-dim": "#38bdf8",
        "background": "#0e1011",
        "on-secondary-fixed": "#001f25",
        "border-muted": "#1a1e20",
        "surface-bright": "#2f3437",
        "tertiary-fixed-dim": "#e0b93f",
        "secondary-container": "#38bdf8",
        "primary-fixed-dim": "#17c46f",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#544600",
        "surface-tint": "#17c46f",
        "on-surface": "#e6e8e8",
      },
      borderRadius: {
        none: "0",
        sm: "0.25rem",
        DEFAULT: "0.375rem",
        md: "0.5rem",
        lg: "0.625rem",
        xl: "0.875rem",
        "2xl": "1.125rem",
        full: "9999px",
      },
      spacing: {
        "stack-sm": "0.5rem",
        "container-max": "1280px",
        "stack-lg": "2rem",
        "stack-md": "1rem",
        "margin-mobile": "1rem",
        "gutter": "1.5rem",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        "display-lg": ["Oswald"],
        "label-caps": ["Inter"],
        "headline-lg": ["Oswald"],
        "body-md": ["Inter"],
        "data-tabular": ["JetBrains Mono"],
      },
      fontSize: {
        "display-lg": ["72px", { lineHeight: "80px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "0.02em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "data-tabular": ["14px", { lineHeight: "20px", fontWeight: "500" }],
      },
    },
  },
  plugins: [forms],
};
